import { getSession } from 'next-auth/client';
import Head from 'next/head'
import Header from '../components/header/Header'
import Login from '../components/login/Login';
import Sidebar from '../components/sidebar/Sidebar';

export default function Home({ session}) {

  if(!session)  return <Login/>;
  return (
    <div className="container">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <main className="flex">
        <Sidebar/>
      </main>
    </div>
  );
}


export async function getServerSideProps(context){
   const session = await getSession(context);

   return {
     props : {
       session
     }
   }
}