import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Let build facebook</h2>
    </div>
  )
}
